[View in Colaboratory](https://colab.research.google.com/github/jorgequintanagonzalez/colab/blob/master/Snippets.ipynb)

# Snippets Python

Texto normal

# CSV

primero cargar la librería de csv *csv*
Después utilizar los procedimientos de leer y escribir Fichero para leer el filename (cadena) y devolver una lista de listas de strings con los valores del csv.
Para escribir pasar la lista de lista de cadenas para escribirlas.


In [0]:
import csv


# Se le pasa el nombre del fichero y devuelve una lista de listas de cadenas o algo así.
def leerFichero (filename):
    with open(filename, 'r',newline='') as csvfile:
        reader = csv.reader(csvfile, delimiter=',',quotechar='|', quoting=csv.QUOTE_MINIMAL)
        listaCadenas=[]
        #Cada fila se devuelve como una lista de cadenas. No se aplica transformación de datos.
        try: 
            for row in reader:
                listaCadenas.append(row)
        except csv.Error as e:
            SystemExit.exit('fichero %s, linea %d: %s' % (filename,reader.line_num,e))        
        return listaCadenas


def escribirFichero(filename,listaCadenas):
    with open(filename, 'w',newline='') as csvfile:
        #El writer retorna el objeto con el que se puede escribir.
        writer = csv.writer(csvfile, delimiter=',',quotechar='|', quoting=csv.QUOTE_MINIMAL)
        for cadena in listaCadenas:
            writer.writerow(cadena)
            
            
#Creamos un fichero, le pasamos una lista de listas de strings que se escriben y luego se leen y se imprimen
filename='prueba.csv'
lista= [['Prueba1','Prueba2','Prueba3'] , ['Prueba4',"Prueba5",'Prueba6']]
escribirFichero(filename, lista)
listadoFinal=leerFichero(filename)
for cadena in listadoFinal:
    print ("c1 :--> "+str(cadena))       

#Graficas - Matlab

creación de gráficas a través del matlab.

1. Lo primero es la creación de una función y la escritura de la misma en pantalla.
2. Se importan las librerías de matlab.
3. Se crea un arange (array con los contenidos numéricos de 0 a 2 en intervalos de 0.01, en total unos doscientos numeros)
4. Se crear el array de resultados con el resultado de la función por cada uno de los puntos anteriores.
5. Se obtiene la figura y el eje al hacer el subplot.
6. Se muestran los valores de los dos arrays de coordenadas.
7. Se pone el texto a los ejes y a la gráfica.
8. Se le pone un grid, se salva y se muestra por pantalla.

In [0]:
import matplotlib
import matplotlib.pyplot as plt
import numpy as np

# Para funciones
# Data for plotting
t = np.arange(0.0, 2.0, 0.01)
s = 1 + np.sin(2 * np.pi * t)

fig, ax = plt.subplots()
ax.plot(t, s)

ax.set(xlabel='time (s)', ylabel='voltage (mV)',
       title='About as simple as it gets, folks')
ax.grid()

fig.savefig("test.png")
plt.show()

En esta siguiente, se crean unas barras horizontales (dos gráficas). Los valores de los ejes serán unos nombres datos (unta tupla de cinco elementos), los valores del otro eje un array de aleatorios.
1. primero se carga la librería
2. Se crea un array con los valores (cinco aleatorios, etc.)
3. Se calculan las posiciones relativas de cada barra.
4. Se crea la figura
5. Se crea la grafica de barra horizontal (se le pasan las posiciones del eje y y llos valores del eje X, además de la alineación)
6. Se ponen los valores del eje y (la tupla)
7. Se pone el titulo del eje X
8. Se pone el titulo de la figura
9. Y se le pone un grid.

En el otro gráfico es lo mismo, pero se crea la parte de error (para los cuantiles o percentiles)

In [0]:
from pylab import *

#rand(5) devuelve 5 aleatorios entre 0 y 1
val = 3+10*rand(5)    # the bar lengths
#arange 5 devuelve un array con cinco elementos [0,1,2,3,4]
pos = arange(5)+.5    # the bar centers on the y axis



figure(1)
# se le pasan las posiciones donde deben estar y los valores que deben de tener.
barh(pos,val, align='center')
yticks(pos, ('Tom', 'Dick', 'Harry', 'Slim', 'Jim'))
xlabel('Performance')
title('How fast do you want to go today?')
grid(True)

figure(2)
barh(pos,val, xerr=rand(5), ecolor='r', align='center')
yticks(pos, ('Tom', 'Dick', 'Harry', 'Slim', 'Jim'))
xlabel('Performance')

show()

# Matlab - Matrices, arrays y demás 

Importar la librería de trabajo

In [0]:
import numpy as np

Crear matriz de ceros (3x3)

In [6]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Crear matriz de unos (3x3)

In [7]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Crear matriz identidad (3x3)

In [8]:
np.identity((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Crear matrices, a través de un array o directamente con matrix

In [10]:
v1 = np.array([[1, -1], [2, 0]])
v2 = np.matrix([0, 1, 2, 3])
print(v1)
print(v2)

[[ 1 -1]
 [ 2  0]]
[[0 1 2 3]]


Trasponer la matriz (dos formas)

In [13]:
v3=np.transpose(v1)
v4=v2.T
print(v1)
print(v3)
print(v2)
print(v4)

[[ 1 -1]
 [ 2  0]]
[[ 1  2]
 [-1  0]]
[[0 1 2 3]]
[[0]
 [1]
 [2]
 [3]]


**Operaciones con matrices:**
1. Suma de matrices
2. Multiplicacion por escalar
3. Negativa
4. Producto
5. Tamaño de la matriz
6. Determinante

In [29]:
m = np.matrix([[1, 2], [3, 4]])
print('Matriz  :'+str(m))
#suma
m2=m+m
print('Suma: '+str(m2))
#multiplicacion por escalar
m2=2*m
print('2*matriz: '+str(m2))
#negativa
m2=-m
print('-Matriz: '+str(m2))
#Tamaño de la matriz
print('Tamaño:'+str(m.shape))
#Producto
m2=m*m
print('Producto MxM:'+str(m2))
#determinante
print('|M|: '+str(np.linalg.det(m)))

Matriz  :[[1 2]
 [3 4]]
Suma: [[2 4]
 [6 8]]
2*matriz: [[2 4]
 [6 8]]
-Matriz: [[-1 -2]
 [-3 -4]]
Tamaño:(2, 2)
Producto MxM:[[ 7 10]
 [15 22]]
|M|: -2.0000000000000004


**Obtener listas de numeros**
1. Arange (obtener listado de numeros normal)
2. Linspace, obtener puntos equiespaciados entre dos cantidades dadas (floats, etc.)
3. Logspace, obtener puntos equiespaciados según una escala logarítmica.

In [30]:
# Imprimir lista de numeros entre 0 y 2 en intervalos de 0.1, 20 numeros
print(np.arange(0.0, 2.0, 0.1))

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9]


In [33]:
# 11 puntos equiespaciados entre 0 y 1
print(np.linspace(0, 1, 11))  

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [34]:
#Obtener  4 puntos equiespaciados según una escala logarítmica entre 10^2 y 10^5
print(np.logspace(2, 5, 4, base=10))

[   100.   1000.  10000. 100000.]


# Generación de comprehensions


Generador de una lista con expresión matemática sencilla (mejor que los map reduce)

In [3]:
no_primes = [j for i in range(2, 100) for j in range(i*2, 1000, i)]
print(no_primes)

[4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204, 206, 208, 210, 212, 214, 216, 218, 220, 222, 224, 226, 228, 230, 232, 234, 236, 238, 240, 242, 244, 246, 248, 250, 252, 254, 256, 258, 260, 262, 264, 266, 268, 270, 272, 274, 276, 278, 280, 282, 284, 286, 288, 290, 292, 294, 296, 298, 300, 302, 304, 306, 308, 310, 312, 314, 316, 318, 320, 322, 324, 326, 328, 330, 332, 334, 336, 338, 340, 342, 344, 346, 348, 350, 352, 354, 356, 358, 360, 362, 364, 366, 368, 370, 372, 374, 376, 378, 380, 382, 384, 386, 388, 390, 392, 394, 396, 398, 400, 402, 404, 406, 408, 410, 412, 414, 416, 418, 420, 422, 

# Iteraciones y Generadores

Iteración sencilla con lista:

In [0]:
cities = ["Paris", "Berlin", "Hamburg", "Frankfurt", "London", "Vienna", "Amsterdam", "Den Haag"]
for location in cities:
     print("location: " + location)

Iteración sencilla con While

In [0]:
other_cities = ["Strasbourg", "Freiburg", "Stuttgart", "Vienna / Wien", "Hannover", "Berlin", "Zurich"]
"""Iterador con un while en vez de un for"""     
city_iterator = iter(other_cities)
while city_iterator:
     try:
          city = next(city_iterator)
          print(city)
     except StopIteration:
          break

Iteración con diccionario

In [0]:
capitals = { "France":"Paris", "Netherlands":"Amsterdam", "Germany":"Berlin", "Switzerland":"Bern", "Austria":"Vienna"}
for country in capitals:
     print("The capital city of " + country + " is " + capitals[country]) 

Generador, con yield devuelve el resultado en cada una de las iteraciones.

In [40]:
def city_generator():
     yield("London")
     yield("Hamburg")
     yield("Konstanz")
     yield("Amsterdam")
     yield("Berlin")
     yield("Zurich")
     yield("Schaffhausen")
     yield("Stuttgart")

# importarle si no existiera from city_generator import city_generator

city = city_generator()
#Obtener un elemento
print(next(city))

#ITerar con un while
while city:
     try:
          print(next(city))
     except StopIteration:
          break


London
Hamburg
Konstanz
Amsterdam
Berlin
Zurich
Schaffhausen
Stuttgart


Imprime los cinco primeros cuadrados.
1. El primer generador genera enteros de forma INFINITA
2. El segundo generador genera los cuadrados de los enteros del otro generador INFINITO también.
3. El tercer procedimiento (en este caso) soporta un numero (límite) y una secuencia. 
Obtiene un iterador sobre la secuencia e itera tantas veces como el limite (con el range) y llama al next del iterador para obtener el siguiente resultado. HAsta el final de la iteración o se acabe el rango (el límite). Al final retorna el array de resultados.
4. Por último se llama al procedimiento con los valores (5 limite de elmentos) y la función generadora de resultados (obtener los cuadrados).
como resultado obtenemos los 5 primeros cuadrados de los numeros enteros

In [57]:
"""Infinite sequence of integers."""
def integers():
     i = 1
     while True:
          yield i
          i = i + 1


def squares():
     for i in integers():
          yield i * i

def take(n, seq):
     """Returns first n values from the given sequence."""
     seq = iter(seq)
     result = []
     try:
          for i in range(n):
               result.append(next(seq))
     except StopIteration:
          pass
     return result

"""Imprime los cinco primeros cuadrados"""
limite=5
print('Numeros:   '+ str([1, 2, 3, 4, 5]) )
print('Cuadrados: '+str(take(limite,squares())))

Numeros:   [1, 2, 3, 4, 5]
Cuadrados: [1, 4, 9, 16, 25]


Fibonacci (con código antes y después del yield)

In [61]:
def fibonacci():
     """Generates an infinite sequence of Fibonacci numbers on demand"""
     a, b = 0, 1
     while True:
          yield a
          """El codigo despues del yield se ejecuta para la siguiente llamada (el valor devuelto es el del yield"""
          a, b = b, a + b

f=fibonacci()

counter = 0
limit=10
for x in f:
     print(x, " ", end="")
     counter += 1
     if (counter > limit): 
          break 
print()

0  1  1  2  3  5  8  13  21  34  55  


**Yield from** como alternativa al for in (los dos generadores son equivalentes)

In [0]:
def gen1():
     for char in "Python":
          yield char
     for i in range(5):
          yield i

def gen2():
     yield from "Python"
     yield from range(5)

Generador fibonacci con otro generador encima para limitar el tamaño de los elementos mostrados

In [62]:
def fibonacci():
     """Ein Fibonacci-Zahlen-Generator"""
     a, b = 0, 1
     while True:
          yield a
          a, b = b, a + b

def firstn(g, n):
     for i in range(n):
          yield next(g)

print(list(firstn(fibonacci(), 10)))

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]


Realizar permutaciones con generador:

1. Primera forma un bucle for llamando al generador (devuelve cadenas)
2. Segunda forma, igual, pero con una lista que es una cadena. (devuelve cadenas)
3. Tercera forma, importando itertools que ya tiene el procedimiento de permutaciones (lo devuelve como lista de cadenas)

In [67]:
""" Permutaciones """

def permutations(items):
     n = len(items)
     if n==0: yield []
     else:
          for i in range(len(items)):
               for cc in permutations(items[:i]+items[i+1:]):
                    yield [items[i]]+cc
#Primera forma
for p in permutations(['r','e','d']): print(''.join(p) + ", ", end="")
print()
# Con una lista de cuatro letras (un string)
for p in permutations(list("game")): print(''.join(p) + ", ", end="")
print()

# Con itertools
import itertools
perms = itertools.permutations(['r','e','d'])
list(perms)


red, rde, erd, edr, dre, der, 
game, gaem, gmae, gmea, geam, gema, agme, agem, amge, ameg, aegm, aemg, mgae, mgea, mage, maeg, mega, meag, egam, egma, eagm, eamg, emga, emag, 


[('r', 'e', 'd'),
 ('r', 'd', 'e'),
 ('e', 'r', 'd'),
 ('e', 'd', 'r'),
 ('d', 'r', 'e'),
 ('d', 'e', 'r')]