[View in Colaboratory](https://colab.research.google.com/github/jorgequintanagonzalez/colab/blob/master/Snippets_python_final.ipynb)

# Snippets Python

Texto normal

# CSV

primero cargar la librería de csv *csv*
Después utilizar los procedimientos de leer y escribir Fichero para leer el filename (cadena) y devolver una lista de listas de strings con los valores del csv.
Para escribir pasar la lista de lista de cadenas para escribirlas.


In [0]:
import csv


# Se le pasa el nombre del fichero y devuelve una lista de listas de cadenas o algo así.
def leerFichero (filename):
    with open(filename, 'r',newline='') as csvfile:
        reader = csv.reader(csvfile, delimiter=',',quotechar='|', quoting=csv.QUOTE_MINIMAL)
        listaCadenas=[]
        #Cada fila se devuelve como una lista de cadenas. No se aplica transformación de datos.
        try: 
            for row in reader:
                listaCadenas.append(row)
        except csv.Error as e:
            SystemExit.exit('fichero %s, linea %d: %s' % (filename,reader.line_num,e))        
        return listaCadenas


def escribirFichero(filename,listaCadenas):
    with open(filename, 'w',newline='') as csvfile:
        #El writer retorna el objeto con el que se puede escribir.
        writer = csv.writer(csvfile, delimiter=',',quotechar='|', quoting=csv.QUOTE_MINIMAL)
        for cadena in listaCadenas:
            writer.writerow(cadena)
            
            
#Creamos un fichero, le pasamos una lista de listas de strings que se escriben y luego se leen y se imprimen
filename='prueba.csv'
lista= [['Prueba1','Prueba2','Prueba3'] , ['Prueba4',"Prueba5",'Prueba6']]
escribirFichero(filename, lista)
listadoFinal=leerFichero(filename)
for cadena in listadoFinal:
    print ("c1 :--> "+str(cadena))       

#Graficas - Matlab

creación de gráficas a través del matlab.

1. Lo primero es la creación de una función y la escritura de la misma en pantalla.
2. Se importan las librerías de matlab.
3. Se crea un arange (array con los contenidos numéricos de 0 a 2 en intervalos de 0.01, en total unos doscientos numeros)
4. Se crear el array de resultados con el resultado de la función por cada uno de los puntos anteriores.
5. Se obtiene la figura y el eje al hacer el subplot.
6. Se muestran los valores de los dos arrays de coordenadas.
7. Se pone el texto a los ejes y a la gráfica.
8. Se le pone un grid, se salva y se muestra por pantalla.

In [0]:
import matplotlib
import matplotlib.pyplot as plt
import numpy as np

# Para funciones
# Data for plotting
t = np.arange(0.0, 2.0, 0.01)
s = 1 + np.sin(2 * np.pi * t)

fig, ax = plt.subplots()
ax.plot(t, s)

ax.set(xlabel='time (s)', ylabel='voltage (mV)',
       title='About as simple as it gets, folks')
ax.grid()

fig.savefig("test.png")
plt.show()

En esta siguiente, se crean unas barras horizontales (dos gráficas). Los valores de los ejes serán unos nombres datos (unta tupla de cinco elementos), los valores del otro eje un array de aleatorios.
1. primero se carga la librería
2. Se crea un array con los valores (cinco aleatorios, etc.)
3. Se calculan las posiciones relativas de cada barra.
4. Se crea la figura
5. Se crea la grafica de barra horizontal (se le pasan las posiciones del eje y y llos valores del eje X, además de la alineación)
6. Se ponen los valores del eje y (la tupla)
7. Se pone el titulo del eje X
8. Se pone el titulo de la figura
9. Y se le pone un grid.

En el otro gráfico es lo mismo, pero se crea la parte de error (para los cuantiles o percentiles)

In [0]:
from pylab import *

#rand(5) devuelve 5 aleatorios entre 0 y 1
val = 3+10*rand(5)    # the bar lengths
#arange 5 devuelve un array con cinco elementos [0,1,2,3,4]
pos = arange(5)+.5    # the bar centers on the y axis



figure(1)
# se le pasan las posiciones donde deben estar y los valores que deben de tener.
barh(pos,val, align='center')
yticks(pos, ('Tom', 'Dick', 'Harry', 'Slim', 'Jim'))
xlabel('Performance')
title('How fast do you want to go today?')
grid(True)

figure(2)
barh(pos,val, xerr=rand(5), ecolor='r', align='center')
yticks(pos, ('Tom', 'Dick', 'Harry', 'Slim', 'Jim'))
xlabel('Performance')

show()

# Matlab - Matrices, arrays y demás 

Importar la librería de trabajo

In [0]:
import numpy as np

Crear matriz de ceros (3x3)

In [6]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Crear matriz de unos (3x3)

In [7]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Crear matriz identidad (3x3)

In [8]:
np.identity((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Crear matrices, a través de un array o directamente con matrix

In [10]:
v1 = np.array([[1, -1], [2, 0]])
v2 = np.matrix([0, 1, 2, 3])
print(v1)
print(v2)

[[ 1 -1]
 [ 2  0]]
[[0 1 2 3]]


Trasponer la matriz (dos formas)

In [13]:
v3=np.transpose(v1)
v4=v2.T
print(v1)
print(v3)
print(v2)
print(v4)

[[ 1 -1]
 [ 2  0]]
[[ 1  2]
 [-1  0]]
[[0 1 2 3]]
[[0]
 [1]
 [2]
 [3]]


**Operaciones con matrices:**
1. Suma de matrices
2. Multiplicacion por escalar
3. Negativa
4. Producto
5. Tamaño de la matriz
6. Determinante

In [29]:
m = np.matrix([[1, 2], [3, 4]])
print('Matriz  :'+str(m))
#suma
m2=m+m
print('Suma: '+str(m2))
#multiplicacion por escalar
m2=2*m
print('2*matriz: '+str(m2))
#negativa
m2=-m
print('-Matriz: '+str(m2))
#Tamaño de la matriz
print('Tamaño:'+str(m.shape))
#Producto
m2=m*m
print('Producto MxM:'+str(m2))
#determinante
print('|M|: '+str(np.linalg.det(m)))

Matriz  :[[1 2]
 [3 4]]
Suma: [[2 4]
 [6 8]]
2*matriz: [[2 4]
 [6 8]]
-Matriz: [[-1 -2]
 [-3 -4]]
Tamaño:(2, 2)
Producto MxM:[[ 7 10]
 [15 22]]
|M|: -2.0000000000000004


**Obtener listas de numeros**
1. Arange (obtener listado de numeros normal)
2. Linspace, obtener puntos equiespaciados entre dos cantidades dadas (floats, etc.)
3. Logspace, obtener puntos equiespaciados según una escala logarítmica.

In [30]:
# Imprimir lista de numeros entre 0 y 2 en intervalos de 0.1, 20 numeros
print(np.arange(0.0, 2.0, 0.1))

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9]


In [33]:
# 11 puntos equiespaciados entre 0 y 1
print(np.linspace(0, 1, 11))  

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [34]:
#Obtener  4 puntos equiespaciados según una escala logarítmica entre 10^2 y 10^5
print(np.logspace(2, 5, 4, base=10))

[   100.   1000.  10000. 100000.]


# Generación de comprehensions


Generador de una lista con expresión matemática sencilla (mejor que los map reduce)

In [68]:
no_primes = [j for i in range(2, 10) for j in range(i*2, 100, i)]
print(no_primes)

[4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64, 68, 72, 76, 80, 84, 88, 92, 96, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 12, 18, 24, 30, 36, 42, 48, 54, 60, 66, 72, 78, 84, 90, 96, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 18, 27, 36, 45, 54, 63, 72, 81, 90, 99]


# Iteraciones y Generadores

Iteración sencilla con lista:

In [0]:
cities = ["Paris", "Berlin", "Hamburg", "Frankfurt", "London", "Vienna", "Amsterdam", "Den Haag"]
for location in cities:
     print("location: " + location)

Iteración sencilla con While

In [0]:
other_cities = ["Strasbourg", "Freiburg", "Stuttgart", "Vienna / Wien", "Hannover", "Berlin", "Zurich"]
"""Iterador con un while en vez de un for"""     
city_iterator = iter(other_cities)
while city_iterator:
     try:
          city = next(city_iterator)
          print(city)
     except StopIteration:
          break

Iteración con diccionario

In [0]:
capitals = { "France":"Paris", "Netherlands":"Amsterdam", "Germany":"Berlin", "Switzerland":"Bern", "Austria":"Vienna"}
for country in capitals:
     print("The capital city of " + country + " is " + capitals[country]) 

Generador, con yield devuelve el resultado en cada una de las iteraciones.

In [40]:
def city_generator():
     yield("London")
     yield("Hamburg")
     yield("Konstanz")
     yield("Amsterdam")
     yield("Berlin")
     yield("Zurich")
     yield("Schaffhausen")
     yield("Stuttgart")

# importarle si no existiera from city_generator import city_generator

city = city_generator()
#Obtener un elemento
print(next(city))

#ITerar con un while
while city:
     try:
          print(next(city))
     except StopIteration:
          break


London
Hamburg
Konstanz
Amsterdam
Berlin
Zurich
Schaffhausen
Stuttgart


Imprime los cinco primeros cuadrados.
1. El primer generador genera enteros de forma INFINITA
2. El segundo generador genera los cuadrados de los enteros del otro generador INFINITO también.
3. El tercer procedimiento (en este caso) soporta un numero (límite) y una secuencia. 
Obtiene un iterador sobre la secuencia e itera tantas veces como el limite (con el range) y llama al next del iterador para obtener el siguiente resultado. HAsta el final de la iteración o se acabe el rango (el límite). Al final retorna el array de resultados.
4. Por último se llama al procedimiento con los valores (5 limite de elmentos) y la función generadora de resultados (obtener los cuadrados).
como resultado obtenemos los 5 primeros cuadrados de los numeros enteros

In [57]:
"""Infinite sequence of integers."""
def integers():
     i = 1
     while True:
          yield i
          i = i + 1


def squares():
     for i in integers():
          yield i * i

def take(n, seq):
     """Returns first n values from the given sequence."""
     seq = iter(seq)
     result = []
     try:
          for i in range(n):
               result.append(next(seq))
     except StopIteration:
          pass
     return result

"""Imprime los cinco primeros cuadrados"""
limite=5
print('Numeros:   '+ str([1, 2, 3, 4, 5]) )
print('Cuadrados: '+str(take(limite,squares())))

Numeros:   [1, 2, 3, 4, 5]
Cuadrados: [1, 4, 9, 16, 25]


Fibonacci (con código antes y después del yield)

In [61]:
def fibonacci():
     """Generates an infinite sequence of Fibonacci numbers on demand"""
     a, b = 0, 1
     while True:
          yield a
          """El codigo despues del yield se ejecuta para la siguiente llamada (el valor devuelto es el del yield"""
          a, b = b, a + b

f=fibonacci()

counter = 0
limit=10
for x in f:
     print(x, " ", end="")
     counter += 1
     if (counter > limit): 
          break 
print()

0  1  1  2  3  5  8  13  21  34  55  


**Yield from** como alternativa al for in (los dos generadores son equivalentes)

In [0]:
def gen1():
     for char in "Python":
          yield char
     for i in range(5):
          yield i

def gen2():
     yield from "Python"
     yield from range(5)

Generador fibonacci con otro generador encima para limitar el tamaño de los elementos mostrados

In [62]:
def fibonacci():
     """Ein Fibonacci-Zahlen-Generator"""
     a, b = 0, 1
     while True:
          yield a
          a, b = b, a + b

def firstn(g, n):
     for i in range(n):
          yield next(g)

print(list(firstn(fibonacci(), 10)))

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]


Realizar permutaciones con generador:

1. Primera forma un bucle for llamando al generador (devuelve cadenas)
2. Segunda forma, igual, pero con una lista que es una cadena. (devuelve cadenas)
3. Tercera forma, importando itertools que ya tiene el procedimiento de permutaciones (lo devuelve como lista de cadenas)

In [67]:
""" Permutaciones """

def permutations(items):
     n = len(items)
     if n==0: yield []
     else:
          for i in range(len(items)):
               for cc in permutations(items[:i]+items[i+1:]):
                    yield [items[i]]+cc
#Primera forma
for p in permutations(['r','e','d']): print(''.join(p) + ", ", end="")
print()
# Con una lista de cuatro letras (un string)
for p in permutations(list("game")): print(''.join(p) + ", ", end="")
print()

# Con itertools
import itertools
perms = itertools.permutations(['r','e','d'])
list(perms)


red, rde, erd, edr, dre, der, 
game, gaem, gmae, gmea, geam, gema, agme, agem, amge, ameg, aegm, aemg, mgae, mgea, mage, maeg, mega, meag, egam, egma, eagm, eamg, emga, emag, 


[('r', 'e', 'd'),
 ('r', 'd', 'e'),
 ('e', 'r', 'd'),
 ('e', 'd', 'r'),
 ('d', 'r', 'e'),
 ('d', 'e', 'r')]

# Base de datos

Primero hay que cargar las librerías de soporte cx_Oracle.
Para ello deben ser cargadas (cuidado 32 bits) a través de pip para instalarlas.



``` 
# Directorio de la versión concreta
cd c:\Users\Administrador\AppData\Local\Programs\Python\Python35-32\
#Actualizar pip si es necesario
python -m pip install -U pip setuptools --proxy=http://user:pass@proxy.sacyl.es:3128
#Instalar libreria de oracle
python -m pip install cx_Oracle --proxy=http://user:pass@proxy.sacyl.es:3128

```

Más información y ejemplos en [ esta web](https://github.com/oracle/python-cx_Oracle/tree/master/samples/tutorial)



In [0]:
import cx_Oracle

Capturar errores de conexión con BBDD y abrir y cerrar la conexión

In [0]:
nombreUsuario='HCEL'
contrasenaUsuario='PRUEBA'
nombre_servidor='servidor.dominio.es'
puerto=1521
instancia='ORCL'
# USER/PASS@SERVES.ES:1521/orcl
cadena_conexion = nombreUsuario+'/'+contrasenaUsuario+'@'+nombreServidor+':'+str(puerto)+'/'+instancia
try: 
    conexion = cx_Oracle.connect(cadena_conexion)
    print(conexion.version)
except cx_Oracle.DatabaseError as e:
    error, = e.args
    if error.code == 1017:
        logger.error('Usuario contraseña no válido.')
        sys.exit()
    else:
        logger.error('Error de conexión con la bbdd.: %s'.format(error))
except: 
    logger.error("Error inesperado:", sys.exc_info()[0])
finally:
    conexion.close()

**Cursores.** Los cursores son iteradores de python
1. Creación del cursor sobre la conexion
2. Parseo, no es necesario, pero es util para poder recoger excepciones antes de tirar la consulta
3. Ejecución de una consulta.
4. Lectura de datos.


In [0]:
#Crear Cursor
cursor = conexion.cursor()
#descripcion del cursor
pprint(cursor.description)

In [0]:
#Parseo
try:
  cursor.parse('SELECT * FROM jobs')
except cx_Oracle.DatabaseError as e:
    error, = e.args
    print('Error de bbdd.: %s'.format(error))


In [0]:
 # execute(statement, [parameters], **keyword_parameters)   
cursor.execute('SELECT * FROM jobs')

In [0]:
#Uso como cualquier iterador los datos
for row in cursor: 
  print(row)

In [0]:
# Podemos también traernos todos los datos o uno a uno
lista_filas=cursor.fetchall()
#Solo uno
lista_una_fila=cursor.fetchone()
# un numero determinado
lista_10=fetchmany(10)

Utilizamos bind variables cuando tenemos multiples consultas sobre algún parametro.
Podemos preparar las consultas antes de ejecutarlas para que vaya más rápido.

In [0]:
# Alternativas con bind variables, se pasan como un diccionario
named_params = {'dept_id':50, 'sal':1000}
query1 = cursor.execute('SELECT * FROM employees WHERE department_id=:dept_id AND salary>:sal', named_params)
query2 = cursor.execute('SELECT * FROM employees WHERE department_id=:dept_id AND salary>:sal', dept_id=50, sal=1000)

In [0]:
#Preparamos las sentencias que hacemos con bind para volver a ejecutarlas varias veces.
cursor.prepare('SELECT * FROM jobs WHERE min_salary>:min')
r = cursor.execute(None, {'min':1000})
#Imprime Cuantos registros lo  cumplen
print(len(cursor.fetchall()))
# La ejecutamos con otros valores
r = cursor.execute(None, {'min':100})
print(len(cursor.fetchall()))
r = cursor.execute(None, {'min':10})
print(len(cursor.fetchall()))

Multiples inserts - ExecuteMany


In [0]:
# Preparar la sentencia con las variables que se van a pasar en el bind
cursor.prepare("INSERT INTO python_modules(module_name, file_path) VALUES (:1, :2)")
# En la ejecución se pasan las variables, la primera sería la consulta (ya esta preparada y por eso esta a none)
# La segunda es una lista con los valores de las variables
M= [[1,2],[]3,4]
cursor.executemany(None, M)
#Hacemos un commit para guardar en la base de datos.
db.commit()

#Otro ejemplo
rows = [ (1, "First" ), (2, "Second" ),
         (3, "Third" ), (4, "Fourth" ),
         (5, "Fifth" ), (6, "Sixth" ),
         (7, "Seventh" ) ]

cur.executemany("insert into mytab(id, data) values (:1, :2)", rows)

**Tipos de datos:**

Oracle
->
cx_Oracle/tipo datos python

VARCHAR2 
NVARCHAR2 
LONG	
->
cx_Oracle.STRING/string

CHAR
->
cx_Oracle.FIXED_CHAR/string

NUMBER
->
cx_Oracle.NUMBER/int

FLOAT
->
float

DATE
->
cx_Oracle.DATETIME/ datetime.datetime

TIMESTAMP
->
cx_Oracle.TIMESTAMP/  datetime.datetime

CLOB
BLOB
->
cx_Oracle.CLOB
cx_Oracle.BLOB/cx_Oracle.LOB



# Serialización y guardado en fichero, Json, Pickle y Shelves

Importamos: 
1. **jsonpickle** para guardar los datos en formato legible json (serialización)
2. **pickle** para guardar los datos en binario serializados
3. **shelve** para guardar los datos serializados en un fichero.

In [0]:
import jsonpickle
import shelve
import pickle

Meter los datos en el serializable con encode y después se guardan en el shelf

In [0]:
#creamos el almacen serializado con el fichero
shelf=shelve.open('datos_listas.dat')
#creamos la lista a guardar
lista_guardar=[1,2,3,4,5,6,7,8,9]

In [0]:
#creamos el objeto serializado con jsonpickle o con pickle (binario)
lista_serializada_Json=jsonpickle.encode(lista)



In [0]:
#Guardamos en el almacen
shelf["lista_guardar_json"]=lista_serializada_Json


In [0]:
# Cerramos el almacen
shelf.close()

Con **pickle** es un poco distinto

1.- Escribir fichero. Haciendo un dump, se pasan los datos, el fichero y una indicación de que use el mejor pickle que pueda para sea versión.
2. Leer el fichero es simplemente un load de ese fichero.

In [0]:
# An arbitrary collection of objects supported by pickle.
data = {
    'a': [1, 2.0, 3, 4+6j],
    'b': ("character string", b"byte string"),
    'c': {None, True, False}
}

#Escribir en el fichero
with open('data.pickle.dat', 'wb') as f:
    # Pickle the 'data' dictionary using the highest protocol available.
    pickle.dump(data, f, pickle.HIGHEST_PROTOCOL)

In [0]:
#Leer un fichero serializado con pickle
with open('data.pickle.dat', 'rb') as f:
    # The protocol version used is detected automatically, so we do not
    # have to specify it.
    data = pickle.load(f)

# Logs

Importar la clase de logs

In [0]:
import logging

Creación del logger al que se le pone un nombre. Luego se asigna un fichero al logger y un formato. Además se le puede dar un nivel al log por defecto y un formato por defecto.

1. Crear el logger con un nombre y un nivel si se desea
2. Crear el fichero de log correspondiente (el manejador)
3. Asociar el nivel y el formateador al manejador.
4. Finalmente asociar los manejadores (ficheros, etc) al logger.
5. Ya podemos usar el log en la aplicación.

In [0]:
# crear un logger, le damos un nombre y le ponemos un nivel de log por defecto
logger=logging.getLogger('Duplicados_Salamanca')
logger.setLevel(logging.DEBUG)

In [0]:
#Crear manejador de log, le asignamos el nombre del fichero y el nivel del fichero
logFile=logging.FileHandler('dupes.log')
logFile.setLevel(logging.INFO)
# crear un formateador
# En este caso, el tiempo, el nivel de log y el mensaje que se envía.
formatter = logging.Formatter('%(asctime)s- %(levelname)s - %(message)s')
# Asignamos al fichero ese formateador
logFile.setFormatter(formatter)


In [0]:
#crear un manejado de consola
ch=logging.StreamHandler(logging.DEBUG)
ch.setFormatter(formatter)

In [0]:
# Añadir los handlers al logger. Le asignamos el fichero de log al logger
logger.addHandler(logFile)
# y el de consola
logger.addHandler(ch)

In [0]:
# Usar el logger
logger.debug('Mensaje con Debug')
logger.info('Mensaje con Info')
logger.warn('Mensaje con Warn')
logger.error('Mensaje con Error')
logger.critical('Mensaje con Critical')
# Introductir variables
logger.info('tiempo pasado: {t} segundos'.format(t=elapsed))
logger.error('Error de conexión con la bbdd.: %s'.format(error))


